### ISSUE TITLE
the pip install command does not run

### ISSUE THREAD

**Issue by HitachiWangNJU** [ecmwf-lab/ai-models-aurora#1]
If I type the install command, it will show:
ERROR: Could not find a version that satisfies the requirement ai-models-aurora (from versions: none)
ERROR: No matching distribution found for ai-models-aurora

**Comment by HCookie** [comment]
Can you try again with the recent pypi pushes?

**Comment by HitachiWangNJU** [comment]
As the developer said that there are another package  named aurora in pip store,
so maybe you can install this package by trying: pip install ai-models-aurora >= 0.0.2
reference:
The plugin was intended to be released on PyPI under the name ai-models-aurora. Unfortunately, this name has been registered by a third party. Therefore, do not install the plugin from the PyPI package name ai-model-aurora, but instead keep a close eye on the [the homepage of the plugin](https://github.com/ecmwf-lab/ai-models-aurora).

**Comment by HCookie** [comment]
If you check the README, that issue has been resolved.
You may now install from pypi
```
pip install ai-models-aurora
```
